apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '<YOUR_GIT_REPO>'  # Replace with your Git repository
    targetRevision: main
    path: gitops/infrastructure/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
