apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tax-calculator-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/tobiakinlade/vault-gitops-platform.git  # UPDATE THIS
    targetRevision: HEAD
    path: kubernetes/base/tax-calculator/frontend
  
  destination:
    server: https://kubernetes.default.svc
    namespace: tax-calculator
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore HPA-controlled replica count
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
